### ISSUE TITLE
First call to emit won't produce a value

### ISSUE THREAD

**Issue by anttih** [purescript-contrib/purescript-aff-coroutines#12]
I think this is a regression either with aff-coroutines or just coroutines.

The code below should print "Hello world" but it won't print anything. If you add the second emit call, it will print it. It won't work with just a single `emit (Right unit)` either.

``` purescript
module Coroutines where

import Prelude
import Control.Monad.Aff (Aff, launchAff)
import Control.Monad.Eff (Eff)
import Control.Monad.Aff.AVar (AVAR)
import Control.Monad.Eff.Exception (EXCEPTION)
import Control.Monad.Eff.Console (CONSOLE)
import Control.Monad.Aff.Console (log)
import Control.Coroutine (Producer, runProcess, consumer, ($$))
import Control.Coroutine.Aff (produce)
import Data.Either (Either(Left))
import Data.Maybe (Maybe(Nothing))

producer :: forall eff. Producer Unit (Aff (avar ∷ AVAR | eff)) Unit
producer = produce \emit → do
  emit (Left unit)
  --emit (Left unit)

main ∷ forall eff. Eff (avar ∷ AVAR, err ∷ EXCEPTION, console ∷ CONSOLE | eff) Unit
main = void $ launchAff $ runProcess (producer $$ (consumer \_ -> log "Hello world" *> pure Nothing))
```

**Comment by paf31** [comment]
The `coroutines` test suite is working without this issue, so this must be caused by something in either `aff` or this library.

**Comment by garyb** [comment]
@anttih what version of `purescript-aff` do you have installed? 2.0.0 or 2.0.1?

**Comment by anttih** [comment]
@garyb I had 2.0.0 and upgrading to 2.0.1 fixes this issue!

**Comment by garyb** [comment]
Great! There was a bug in `Aff`'s `Parallel` instance that was fixed. It is a little strange bower pulled in the old version though - maybe you checked it out before we made the 2.0.1 release?

**Comment by anttih** [comment]
Yeah maybe I did bower update before the fixed version or it just didn't fetch the new version.
